from turtle import *
t = Turtle()
def makeSqaure(x):
    i = 0
    while i<4:
        t.forward(x)
        t.right(90)
        i=i+1
def makeX(x,y,size):
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.goto(x+size,y-size)
    t.penup()
    t.goto(x+size,y)
    t.pendown()
    t.goto(x,y-size)
def makeBoard():
    t.penup()
    t.left(90)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.pendown()
    makeSqaure(150)
    t.penup()
    t.goto(50,0)
    t.pendown()
    t.forward(150)
    t.penup()
    t.goto(0,0)
    t.pendown()
    t.forward(150)
    t.penup()
    t.goto(-50,50)
    t.pendown()
    t.right(90)
    t.forward(150)
    t.penup()
    t.goto(-50,100)
    t.pendown()
    t.forward(150)
    t.penup()
    x = 150
    t.goto(300,x)
    i = 0;
    while i<2:
        t.pendown()
        makeSqaure(50)
        x = x - 50
        t.goto(300,x)
        i=i+1
    makeX(300,150,50)
    t.penup()
    t.goto(325,100)
    t.pendown()
    t.circle(-20)
    t.penup()
    t.goto(300,50)
    t.fillcolor('pink')
    t.pendown()
    t.begin_fill()
    makeSqaure(50)
    t.end_fill()
makeBoard()
